# -*- coding: utf-8 -*-

"""
Anki Add-on: Hotkey to Auto-rate Based on Elapsed Time

Module-level entry point for the add-on into Anki 2.1.x

Please do not edit this file if you are not sure what you are doing.

Copyright: (c) 2018 Glutanimate <https://glutanimate.com/>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from . import reviewer_auto_rate_hotkey
